const dashboardElements = {
	dashboardBody: document.getElementById('dashboardBody'),
	dashboardSidebar: document.getElementById('dashboardSidebar'),
	userName: document.getElementById('userName'),
	userImage: document.getElementById('userImage'),
	totalUsers: document.getElementById('totalUsers'),
	totalUsersVerified: document.getElementById('totalUsersVerified'),
	totalUsersPending: document.getElementById('totalUsersPending'),
	totalNews: document.getElementById('totalNewsletter'),
	activeNews: document.getElementById('activeNewsLetter'),
	blockedNews: document.getElementById('blockedNewsLetter'),
	totalVoluenteer: document.getElementById('totalVoluenteer'),
	pendingVoluenteer: document.getElementById('pendingVoluenteer'),
	approvedVoluenteer: document.getElementById('approvedVoluenteer'),
	sidebarToggle: document.getElementById('sidebarToggle'),
	sidebarOverlay: document.getElementById('sidebarOverlay'),
	sidebar: document.querySelector('.sidebar'),
	userVerificationChart: document.getElementById('userVerificationChart'),
	newsletterChart: document.getElementById('newsletterChart'),
	voluenteerList: document.getElementById('voluenteerList'),
	storageUsed: document.getElementById('storageUsed'),
	bandwidth: document.getElementById('bandwidth'),
	assetsCount: document.getElementById('assetsCount'),
	apiLimit: document.getElementById('apiLimit'),
	creditLimit: document.getElementById('creditLimit'),
};

export default dashboardElements;
