const contactElements = {
	contactSidebar: document.getElementById('contactSidebar'),
	contactBody: document.getElementById('contactBody'),
	toastSection: document.getElementById('toastSection'),
	userName: document.getElementById('userName'),
	userImage: document.getElementById('userImage'),
	totalMessages: document.getElementById('totalMessages'),
	totalNewMessages: document.getElementById('totalNewMessages'),
	userMessages: document.getElementById('userMessages'),
	guestMessages: document.getElementById('guestMessages'),
	messageContainer: document.getElementById('messageContainer'),
	confirmDeleteBtn: document.getElementById('confirmDeleteBtn'),
	deleteModal: document.getElementById('deleteModal'),
	messageModal: document.getElementById('messageDetails'),
	modalSenderName: document.getElementById('modalSenderName'),
	modalSenderEmail: document.getElementById('modalSenderEmail'),
	modalMessageStatus: document.getElementById('modalMessageStatus'),
	modalUserType: document.getElementById('modalUserType'),
	modalMessageTime: document.getElementById('modalMessageTime'),
	modalMessageText: document.getElementById('modalMessageText'),
	modalReceivedDate: document.getElementById('modalReceivedDate'),
	modalReceivedTime: document.getElementById('modalReceivedTime'),
	userInfoSection: document.getElementById('userInfoSection'),
	userNameModal: document.getElementById('userNameModal'),
	userStatus: document.getElementById('userStatus'),
	userJoinDate: document.getElementById('userJoinDate'),
	userMessageCount: document.getElementById('userMessageCount'),
	messageSubject: document.getElementById('messageSubject'),
	modalSenderAvatar: document.getElementById('modalSenderAvatar'),
	contactSearch: document.getElementById('contactSearch'),
};

export default contactElements;
