const volunteerElements = {
	volunteerBody: document.getElementById('volunteerBody'),
	volunteerSidebar: document.getElementById('volunteerSidebar'),
	toastSection: document.getElementById('toastSection'),
	userName: document.getElementById('userName'),
	userImage: document.getElementById('userImage'),
	totalPending: document.getElementById('totalPending'),
	totalApproved: document.getElementById('totalApproved'),
	totalRejected: document.getElementById('totalRejected'),
	totalVolunteers: document.getElementById('totalVolunteers'),
	volunteerContainer: document.getElementById('volunteerContainer'),
	volunteerDetails: document.getElementById('volunteerDetails'),
	volunteerName: document.getElementById('volunteerName'),
	modalApplicantName: document.getElementById('modalApplicantName'),
	modalApplicantEmail: document.getElementById('modalApplicantEmail'),
	userAvattar: document.getElementById('userAvattar'),
	modalApplicationStatus: document.getElementById('modalApplicationStatus'),
	modalApplicationTime: document.getElementById('modalApplicationTime'),
	userJoinDate: document.getElementById('userJoinDate'),
	totalApplications: document.getElementById('totalApplications'),
	modalAvailability: document.getElementById('modalAvailability'),
	modalMotivation: document.getElementById('modalMotivation'),
	modalSubmittedDate: document.getElementById('modalSubmittedDate'),
	modalSubmittedTime: document.getElementById('modalSubmittedTime'),
	modalSkills: document.getElementById('modalSkills'),
	modalFooter: document.getElementById('modalFooter'),
	approveBtn: document.getElementById('approveBtn'),
	rejectBtn: document.getElementById('rejectBtn'),
};

export default volunteerElements;
